language: node_js
node_js:
  - '10'
  - '12'
before_script:
  - npm run lint
install:
  - npm install --ignore-engines
script:
  - npm test
  - npm run coverage:upload
after_success:
  - npm run build:js
  - npm run semantic-release
